import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div class="flex flex-col">
        <main className="bg-yellow-10">
          <div className="container relative mt-7">
            <div className="flex flex-col md:flex-row justify-between">
              <div className="flex-1 flex-col justify-between">
                <h1>We are NorthStar</h1>
              </div>
              <div
                id="hero-img"
                className="w-9/12 md:w-6/12 steps mt-120 md:-mt-230 m-auto"
              ></div>
            </div>
          </div>
        </main>
      </div>
    </>
  )
}
